### ISSUE TITLE
Client and Server generate different configs (minor)

### ISSUE THREAD

**Issue by MissPotato** [YUNG-GANG/YUNGs-Better-Desert-Temples#19]
BCLib was complaining that the client and server had different configs, which was very weird to me as I had just made both the server and client. No configs had been even generated before I started either or. 

I used WinMerge (a windows diff finder) to compare the two config folders and noticed that both "armorstands.json" and "itemframes.json" do not generate in the same order for client and dedicated servers.

Example of itemframes: 
https://i.imgur.com/Q79xFQt.png

The same applies for Better Stronghold's "armorstands.json", "itemframes.json", "ores.json" and "rareblocks.json"

I highly doubt this is important, but it was odd so I figured I'd mention it.

**Comment by yungnickyoung** [comment]
I think this is because Gson's serialization makes no guarantee about order of key/value pairs in objects, which makes sense considering order doesn't matter according to the JSON standard. If anything it seems odd BCLib would care about ordering within JSON objects, although I'm guessing it's just running file diffs.

In either case, yeah this shouldn't cause any issues!
