### ISSUE TITLE
Question: 1.20.1 Support

### ISSUE THREAD

**Issue by Aetrnl94** [YUNG-GANG/YUNGs-Better-Desert-Temples#24]
Hi, I love your mods but I'm playing the latest versions of MC now. Is there any chance that you can at least let us know if you have plans to update your Yung mods to more recent iterations of MC? 
(I play Forge version)
Thanks!

**Comment by wilsontulus** [comment]
There are 2 ways to get a pre-compiled, ready to use 1.20.x version of YUNG's mods:
- Subscribe to YUNG's Patreon with Better tier or higher,
- Become a booster of YUNG GANG discord server.

Otherwise you can just compile YUNG's API and every YUNG's mods you wanted to run in 1.20. It's the same as the ones from Patreon and Discord, except it's only available in source form instead. Look for branch named "1.20", if it's there, you're free to compile it yourself.
