### ISSUE TITLE
Lag on entities 

### ISSUE THREAD

**Issue by jochuan** [YUNG-GANG/YUNGs-Better-Desert-Temples#6]
This mod is causing all entities to lag. When i try to place a spawn egg in creative it takes around 6 seconds for the mobs to appear, the same when i am trying to hit mobs or open chests. Its strange for a world gen mod to be causing that but i am sure that yungs better desert temples is the culprit since i tested every mod that have one by one (I am using around 100 mods, it was a hell to find this).
I am playing on 1.18.2 with the 1.3 version of the mod and forge 40.1.57 and my yungs api version is 2.0.8.

**Comment by alkerss** [comment]
I ran into similar issues, not as severe with the lag, but flying around in creative generating new chunks I get ticks that take 250-900 ms to load, at a 5-40 second interval.
I confirmed it to be a direct result of Better Desert Temple. Tested with both 1.2 and 1.3. 
I was also using Forge 40.1.57 and yungs api 2.0.8
The confusing part is that this happens no matter what biomes are around me. Even on a new world with no desert biomes even remotely close to me, it still creates tick lag. But the lag only happened while generating new chunks for me. I didn't observe any lag while standing still.

I'd post the modlist, but I'm unsure of how to do that. Plus I doubt it would be much use since I had around 180 mods during this testing.

**Comment by awesomedeity** [comment]
I also ran into the entity lag issue trying to build a modpack with my husband. After some testing on my husbands version of the modpack we definitely confirmed a connection to Better Desert Temples. We also noticed the same problem only less severe when using the other Yung's mods with the compat data packs for Repurposed Structures, even when Desert Temples wasn't installed. On my version of the pack I (which had more mods installed) I removed the Desert Temples and the compat data packs but my entity lag was still through the roof. I've started a fresh modpack  and slowly started adding mods in to try and figure out exactly where the issue is. So far I have confirmed that Desert Temples works fine on it's own. I currently have Better Desert Temple, Witch Huts, Strongholds, and Mineshafts in the pack with Repurposed Structures and all three compat data packs (using Openloader). The entity lag has not appeared yet with just those mods installed. (Also had NBT Deadlock Begone installed, RS requires it.)

**Comment by yungnickyoung** [comment]
If you can, please continue trying to find which mod causes lag when using Better Desert Temples. That would be tremendously helpful in fixing this issue.

**Comment by awesomedeity** [comment]
I've been slowly rebuilding my pack and I haven't reproduced the issue so far. I made my husband pull up the pack he had issues with and re add Better Desert Temples with and without the compat pack but even though we were able to reproduce the issue the first day we can't reproduce it now. He doesn't remember if he updated anything.

**Comment by yungnickyoung** [comment]
Please try with v1.3.1 and see if the issue persists!

**Comment by awesomedeity** [comment]
I don't know about everyone else but my problem seems to have been fixed for a while and I never did figure out why.

**Comment by jochuan** [comment]
Looks like the problem was fixed for me
